name: getx_assesment
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Internet and Logger
  dio: ^5.8.0+1
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0

  #Animation
  lottie: ^3.3.1
  shimmer: ^3.0.0

  #State Management
  get: ^4.7.2

  #UI
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  flutter_easyloading: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
